environments:
  path: /location/of/where/the/ansible/inventories/lives
  helper: environments.yaml
ansible_playbook:
  bin_path: /location/of/ansible
  working_directory: /location/of/where/the/ansible-playbook/must/be/executed
  playbooks_path: /location/of/playbooks
