environments:
  path: /location/of/where/the/ansible/inventories/lives
  helper: environments.yaml
ansible:
  working_directory: /location/of/where/the/ansible-playbook/must/be/executed
  run:
    bin_path: /location/of/ansible/command
  playbook:
    bin_path: /location/of/ansible-playbook/command
    playbooks_path: /location/of/playbooks
